<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Album_couvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Album_couvertureRepository extends EntityRepository
{
}
