<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Album_profilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Album_profilRepository extends EntityRepository
{
}
