app_login:
  path : /
  defaults:  { _controller: AppBundle:Login:Login }

app_action_login:
  path : /login/action
  defaults:  { _controller: AppBundle:Login:Action_Login }

app_register:
  path : /register
  defaults:  { _controller: AppBundle:Register:Register }

app_confirmed_register:
  path : /confirmation/account/{user_id}/{private_key}
  defaults:  { _controller: AppBundle:Confirmed:Confirmed }

app_profil:
  path : /profil
  defaults:  { _controller: AppBundle:Profile:Show }

app_mur:
  path : /home
  defaults:  { _controller: AppBundle:Article:Index }

app_action_disconnect:
  path : /disconnect
  defaults:  { _controller: AppBundle:Login:Disconnect_Login }

app_action_update_profil:
  path : /changeProfil/action
  defaults:  { _controller: AppBundle:Article:Addphoto }

app_action_couverture:
  path : /action/couverture
  defaults:  { _controller: AppBundle:Article:Action_couverture }
